name: "CLA"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: 
      - opened 
      - closed 
      - synchronize

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read and agree to the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_TOKEN }}
        with:
          path-to-document: 'https://github.com/ecadlabs/ecadlabs-cla/blob/main/ECAD_Labs_CLA.md'
          branch: 'main'
          allowlist: '@ecadlabs/ecad-team'
          custom-notsigned-prcomment: 'Thank you for your contribution. Like many open-source projects, we require that contributors sign a [Contributor License Agreement](https://github.com/ecadlabs/ecadlabs-cla/blob/main/ECAD_Labs_CLA.md) (based on the Apache Foundation CLA). Please sign the Taqueria project CLA by posting a Pull Request comment of the text below:'
          custom-pr-sign-comment: 'I have read and agree to the CLA'
          remote-organization-name: 'ecadlabs'
          remote-repository-name: 'ecadlabs-cla'