name: VSCode Extension

on:
  workflow_call:
    inputs:
      prerelease:
        required: false
        type: string
      deno-dir:
        default: '~/.deno'
        type: string
      deno-version:
        required: true
        type: string
    secrets:
      GCP_PROJECT:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      VSCE_PAT:
        required: true
    outputs:
      vsixGcsUrl:
        description: "The download URL for the VSIX artifact in GCS"
        value: ${{ jobs.test-build.outputs.vsixGcsUrl }}
      artifactFilename:
        description: "The vsix artifact file name"
        value: ${{ jobs.test-build.outputs.artifactFilename }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  DENO_DIR: ${{ inputs.deno-dir }}
  GIT_WORKSPACE: taqueria-vscode-extension

jobs:
  test-build:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Test and Package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      artifactFilename: ${{ steps.setArtifactFilename.outputs.filename }}
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
      vsixGcsUrl: ${{ steps.publicUrl.outputs.vsixGcsUrl }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ${{ DENO_DIR }}
          key: ${{ runner.os }}-deno-${{ hashFiles('deno-lock.json') }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: "npm"

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ inputs.deno-version }}"

      - name: Attempt to rebuild
        run: npm rebuild | true

      - name: Add working dir to PATH
        run: echo "$(pwd)" >> $GITHUB_PATH

      - run: npm ci

      - name: Build all
        run: |
          npm run build-types
          npm run build:packages
      
      - name: Compile TS
        run: npm run compile:test --workspace ${{ env.GIT_WORKSPACE }}
      
      # - name: Run Unit Tests on Linux
      #   run: xvfb-run -a npm test --workspace ${{ env.GIT_WORKSPACE }}

      - name: Package VSCode Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1.0.4
        with:
          pat: stub
          dryRun: true
          yarn: true
          packagePath: ${{ env.GIT_WORKSPACE }}
          preRelease: true   
      - id: setArtifactFilename
        run: echo "::set-output name=filename::taqueria-vscode-${{ github.head_ref || github.ref_name }}-ubuntu-latest"

      - name: Authenticate with GCP
        id: gcp-auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT }}/locations/global/workloadIdentityPools/github-actions-storage-pool/providers/github-actions-oidc-provider"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Upload binary to GCP
        id: uploadFile
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: ${{ steps.packageExtension.outputs.vsixPath }}
          destination: "taqueria-artifacts/${{ github.ref }}/${{ github.sha }}/${{ steps.setArtifactFilename.outputs.filename }}"

      - name: Set package public url
        id: publicUrl
        run: |
          echo "::set-output name=vsixGcsUrl::https://storage.googleapis.com/taqueria-artifacts/${{ steps.uploadFile.outputs.uploaded }}"

  publish-marketplace:
    name: Publish VSCode Extension
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - test-build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: "npm"

      - name: Add working dir to PATH
        run: echo "$(pwd)" >> $GITHUB_PATH
      
      - run: npm ci

      - name: Build all
        run: |
          npm run build-types
          npm run build:packages
      
      - name: Compile TS
        run: npm run compile --workspace ${{ env.GIT_WORKSPACE }}

      # Separate steps for prerelease and release workflows
      - name: Publish as pre-release
        if: ${{ inputs.prerelease }}
        uses: HaaLeo/publish-vscode-extension@v1.0.4
        with:
          pat: ${{ secrets.VSCE_PAT }}
          yarn: true
          packagePath: ${{ env.GIT_WORKSPACE }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: true

      - name: Publish as official release
        if: ${{ !inputs.prerelease && !github.event.release.prerelease && github.event.action == 'published' }}
        uses: HaaLeo/publish-vscode-extension@v1.0.4
        with:
          pat: ${{ secrets.VSCE_PAT }}
          yarn: true
          packagePath: ${{ env.GIT_WORKSPACE }}
          registryUrl: https://marketplace.visualstudio.com
          